spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workhub_dev
    username: postgres
    password: postgres
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:workhub}
    password: ${RABBITMQ_PASSWORD:workhub}

logging:
  level:
    com.workhub: DEBUG
