spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workhub_dev
    username: postgres
    password: postgres
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.workhub: DEBUG
